name: Create Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Fix permissions
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build javadoc

      - name: Copy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: build/docs/javadoc

      - name: Write version to file
        run: ./gradlew currentVersion

      - name: Set version in script
        run: echo "VERSION=$(cat build/version.txt)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: (CI) gdx-TinyVG ${{ env.VERSION }}
          draft: false
          prerelease: true

      - name: Upload jar release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/gdx-TinyVG-${{ env.VERSION }}.jar
          asset_name: gdx-TinyVG-${{ env.VERSION }}.jar
          asset_content_type: application/x-java-archive
